version: "3"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=wilmion_db
      - POSTGRES_USER=wilmion
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "5050:80"
